ALTER TABLE public.quick_edit_jobs
  ADD COLUMN IF NOT EXISTS plan JSONB,
  ADD COLUMN IF NOT EXISTS tool_used TEXT,
  ADD COLUMN IF NOT EXISTS tool_params JSONB,
  ADD COLUMN IF NOT EXISTS used_fallback BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS preview_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS confidence TEXT,
  ADD COLUMN IF NOT EXISTS preview_ms INTEGER,
  ADD COLUMN IF NOT EXISTS uploaded_file_url TEXT,
  ADD COLUMN IF NOT EXISTS changes_count INTEGER;